# Projet 4: Anticipez les besoins en consommation électrique des bâtiments
## Notebook de preprocessing
*Julie Neury-ormanni*

## Sommaire <a class="anchor" id="sommaire"></a>
## [Import des librairies](#1)<a class="anchor" id="sommaire"></a>
## [Chargement des données](#2)<a class="anchor" id="sommaire"></a>
## [Préparation des données](#3)<a class="anchor" id="sommaire"></a>
### [Sélection des variables pour la modélisation](#4)<a class="anchor" id="sommaire"></a>
## [](#5)<a class="anchor" id="sommaire"></a>

------

## [Import des librairies](#sommaire)<a class="anchor" id="1"></a>

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## [Chargement des données](#sommaire)<a class="anchor" id="2"></a>

In [3]:
df = pd.read_csv(r'C:\Users\neury\Documents\Python\P4\sorties\df_clean.csv')

In [4]:
df.drop(columns = ['Unnamed: 0'], inplace = True)

In [5]:
df.head()

,OSEBuildingID,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,CouncilDistrictCode,...,SecondLargestPropertyUseTypeGFAlog,ThirdLargestPropertyUseTypeGFAlog,SiteEUI(kBtu/sf)log,SiteEnergyUse(kBtu)log,SteamUse(kBtu)log,Electricity(kBtu)log,NaturalGas(kBtu)log,TotalGHGEmissionslog,GHGEmissionsIntensitylog,Otherlog
0,61,Multifamily LR (1-4),Low-Rise Multifamily,GATEWOOD APTS,107 PINE ST,SEATTLE,WA,98101.0,1975700600,7,...,9.231319,0.000000,4.127134,14.898447,13.727748,14.186288,13.285441,4.727919,1.160021,0.0
1,266,Multifamily LR (1-4),Low-Rise Multifamily,WEST SEATTLE COMM. RESOURCE CENTER/FOOD BANK A...,6500 35TH AVE SW,SEATTLE,WA,98126.0,9271000000,1,...,0.000000,0.000000,3.190476,14.008238,0.000000,14.008279,0.000000,2.246015,0.058269,0.0
2,325,NonResidential,Retail Store,WESTLAKE MALL RETAIL PORTION,400 PINE ST,SEATTLE,WA,98101.0,659000005,7,...,0.000000,0.000000,4.120662,16.107917,0.000000,16.107958,0.000000,4.248638,0.215111,0.0
3,400,NonResidential,Small- and Mid-Sized Office,GALLAND & SENECA BUILDINGS,1201 2ND AVE,SEATTLE,WA,98101.0,1974700175,7,...,10.162809,0.000000,4.209160,15.691288,0.000000,15.685505,10.542548,3.876189,0.182322,0.0
4,442,NonResidential,Large Office,KING BROADCASTING,333 DEXTER AVE N,SEATTLE,WA,98109.0,1991200870,7,...,10.541518,9.320718,4.670958,16.634519,0.000000,16.634560,0.000000,4.769328,0.207014,0.0

## [Préparation des données](#sommaire)<a class="anchor" id="3"></a>

### [Sélection des variables pour la modélisation](#sommaire)<a class="anchor" id="4"></a>

In [6]:
col_for_mod = ['OSEBuildingID',
 'BuildingType',
 'PrimaryPropertyType',
 'Neighborhood',
 'YearBuilt',
 'NumberofBuildingslog',
 'NumberofFloorslog',
 'PropertyGFATotallog',
 'PropertyGFAParkinglog',
 'SecondLargestPropertyUseTypeGFAlog',
 'ThirdLargestPropertyUseTypeGFAlog',
 'SiteEnergyUse(kBtu)log',
 'SteamUse(kBtu)log',
 'Electricity(kBtu)log',
 'NaturalGas(kBtu)log',
 'TotalGHGEmissionslog',
 'Otherlog',
 'ENERGYSTARScore']

In [7]:
df_mod = df[col_for_mod]

In [8]:
df_mod.head()

,OSEBuildingID,BuildingType,PrimaryPropertyType,Neighborhood,YearBuilt,NumberofBuildingslog,NumberofFloorslog,PropertyGFATotallog,PropertyGFAParkinglog,SecondLargestPropertyUseTypeGFAlog,ThirdLargestPropertyUseTypeGFAlog,SiteEnergyUse(kBtu)log,SteamUse(kBtu)log,Electricity(kBtu)log,NaturalGas(kBtu)log,TotalGHGEmissionslog,Otherlog,ENERGYSTARScore
0,61,Multifamily LR (1-4),Low-Rise Multifamily,downtown,1900,0.693147,1.609438,10.786924,0.000000,9.231319,0.000000,14.898447,13.727748,14.186288,13.285441,4.727919,0.0,75.0
1,266,Multifamily LR (1-4),Low-Rise Multifamily,delridge,2007,0.693147,1.609438,10.861592,0.000000,0.000000,0.000000,14.008238,0.000000,14.008279,0.000000,2.246015,0.0,85.0
2,325,NonResidential,Retail Store,downtown,1989,0.693147,1.609438,11.617988,0.000000,0.000000,0.000000,16.107917,0.000000,16.107958,0.000000,4.248638,0.0,91.0
3,400,NonResidential,Small- and Mid-Sized Office,downtown,1906,0.693147,1.945910,11.496501,10.162809,10.162809,0.000000,15.691288,0.000000,15.685505,10.542548,3.876189,0.0,45.0
4,442,NonResidential,Large Office,lake union,1947,0.693147,1.609438,12.174525,10.541518,10.541518,9.320718,16.634519,0.000000,16.634560,0.000000,4.769328,0.0,59.0

### [One Hot encoding](#sommaire)<a class="anchor" id="5"></a>

In [9]:
col_to_encod = ['BuildingType',
 'PrimaryPropertyType',
 'Neighborhood']

In [10]:
enc = OneHotEncoder(sparse = False)

In [11]:
new_features_names = pd.get_dummies(df_mod[col_to_encod]).columns.tolist()

In [12]:
encoded = pd.DataFrame(enc.fit_transform(df_mod[col_to_encod]), columns=new_features_names)
encoded.index = df_mod.index
encoded

,BuildingType_Campus,BuildingType_Multifamily HR (10+),BuildingType_Multifamily LR (1-4),BuildingType_Multifamily MR (5-9),BuildingType_NonResidential,BuildingType_Restaurant,BuildingType_SPS-District K-12,PrimaryPropertyType_Distribution Center,PrimaryPropertyType_High-Rise Multifamily,PrimaryPropertyType_Hospital,...,Neighborhood_downtown,Neighborhood_east,Neighborhood_greater duwamish,Neighborhood_lake union,Neighborhood_magnolia / queen anne,Neighborhood_north,Neighborhood_northeast,Neighborhood_northwest,Neighborhood_southeast,Neighborhood_southwest
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3249,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3250,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3251,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3252,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3253,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
all_quant = pd.concat([df_mod.drop(columns = col_to_encod),encoded], axis = 1)

In [14]:
all_quant.shape

(3254, 59)

### Séparation des données

In [15]:
all_quant.head()

,OSEBuildingID,YearBuilt,NumberofBuildingslog,NumberofFloorslog,PropertyGFATotallog,PropertyGFAParkinglog,SecondLargestPropertyUseTypeGFAlog,ThirdLargestPropertyUseTypeGFAlog,SiteEnergyUse(kBtu)log,SteamUse(kBtu)log,...,Neighborhood_downtown,Neighborhood_east,Neighborhood_greater duwamish,Neighborhood_lake union,Neighborhood_magnolia / queen anne,Neighborhood_north,Neighborhood_northeast,Neighborhood_northwest,Neighborhood_southeast,Neighborhood_southwest
0,61,1900,0.693147,1.609438,10.786924,0.000000,9.231319,0.000000,14.898447,13.727748,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,266,2007,0.693147,1.609438,10.861592,0.000000,0.000000,0.000000,14.008238,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,325,1989,0.693147,1.609438,11.617988,0.000000,0.000000,0.000000,16.107917,0.000000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,400,1906,0.693147,1.945910,11.496501,10.162809,10.162809,0.000000,15.691288,0.000000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,442,1947,0.693147,1.609438,12.174525,10.541518,10.541518,9.320718,16.634519,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
train, test = train_test_split(all_quant, test_size = 0.3, random_state = 4)

In [17]:
print(train.shape)
print(test.shape)

(2277, 59)
(977, 59)

### Standardisation des variables

In [18]:
list_col_num = [col_num for col_num in all_quant.columns if col_num not in new_features_names + ['OSEBuildingID','ENERGYSTARScore']]

In [19]:
train_std = train.copy()
test_std = test.copy()

In [20]:
mod_scaler = StandardScaler()
train_std[list_col_num] = mod_scaler.fit_transform(train[list_col_num])
test_std[list_col_num] = mod_scaler.transform(test[list_col_num])

In [21]:
train_std

,OSEBuildingID,YearBuilt,NumberofBuildingslog,NumberofFloorslog,PropertyGFATotallog,PropertyGFAParkinglog,SecondLargestPropertyUseTypeGFAlog,ThirdLargestPropertyUseTypeGFAlog,SiteEnergyUse(kBtu)log,SteamUse(kBtu)log,...,Neighborhood_downtown,Neighborhood_east,Neighborhood_greater duwamish,Neighborhood_lake union,Neighborhood_magnolia / queen anne,Neighborhood_north,Neighborhood_northeast,Neighborhood_northwest,Neighborhood_southeast,Neighborhood_southwest
3176,49999,1.376734,-0.04318,0.938722,0.631259,-0.412584,-0.693080,-0.427928,0.134654,-0.202940,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
24,21796,-1.876551,-0.04318,-1.519583,0.487491,-0.412584,-0.693080,-0.427928,0.154442,-0.202940,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1822,23653,0.630568,-0.04318,-0.290431,-0.140095,-0.412584,-0.693080,-0.427928,0.060586,-0.202940,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
282,401,-1.130385,-0.04318,2.732586,1.992258,-0.412584,-0.693080,-0.427928,2.429518,5.612576,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2203,25065,0.690261,-0.04318,0.428577,1.265797,-0.412584,-0.693080,2.755896,0.579289,-0.202940,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1921,24029,0.391795,-0.04318,-0.290431,-1.023998,-0.412584,-0.693080,-0.427928,-1.386702,-0.202940,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
709,19695,0.958881,-0.04318,-0.290431,-0.445955,-0.412584,-0.693080,-0.427928,-0.565969,-0.202940,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2487,26130,-0.234985,-0.04318,0.428577,-0.198571,-0.412584,-0.693080,-0.427928,0.200669,-0.202940,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
174,238,-0.324525,-0.04318,-0.800575,0.583962,-0.412584,1.596421,2.520497,1.312385,-0.202940,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1146,21177,0.541028,-0.04318,-0.290431,-0.372570,-0.412584,-0.693080,-0.427928,0.068711,-0.202940,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [22]:
train_std.to_csv(r'C:\Users\neury\Documents\Python\P4\entrees\train.csv')

In [23]:
test_std.to_csv(r'C:\Users\neury\Documents\Python\P4\entrees\test.csv')

In [101]:
col_to_estim = ['SiteEnergyUse(kBtu)log',
 'SteamUse(kBtu)log',
 'Electricity(kBtu)log',
 'NaturalGas(kBtu)log',
 'TotalGHGEmissionslog',
 'Otherlog']